[package]
name = "anyinput"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.2.1"

# python bindings
pyo3 = { version = "0.21", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
bindings = "pyo3"